server:
  port: 8888

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\DEV\04_project\HotsixBoot
    web:
      resources:
        static-locations: classpath:/profileImages/

  ## jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        format_sql: 'true'
        hql:
          bulk_id_strategy: 'org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy'



jwt:


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

image:


  add-resource-locations: classpath:/static/profileImages/
  add-resource-handler: /profileImages/**


  image-dir: src/main/resources/static/profileImages
  image-url: http://localhost:8888/profileImages/

# Logging Level
logging:
  level:
    root: info



